spring:
  jpa:
    hibernate.ddl-auto: create-drop
    hibernate.use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://avnadmin:AVNS_1gD9KqzbEiKtQttXCdd@mysql-21ae8973-ahmad-7115.a.aivencloud.com:17299/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_1gD9KqzbEiKtQttXCdd
    
    
  
    
     #ddl-auto:   none update  create-drop  create
      # server:
  #port: 8081
  
  
  logging:
  file:
    name: logs/myapp.log # Sets specific filename and path [5, 14]
  logback:
    rollingpolicy:
      max-file-size: 10MB # Optional: limits file size [15]
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.gz # Optional: archives logs [15]
  level:
    root: INFO # Optional: sets logging level [3, 7]
    com.example.package: DEBUG # Optional: sets package specific level [3]

